### ISSUE TITLE
Text Processing: match and parse "config props" within MD (Rowan's "noting" scenario)

### ISSUE THREAD

**Issue by philcockfield** [cellplatform/platform-0.2.0#84]
`module:` sys.data.text
["uinst" - Universal Syntax Tree](https://github.com/syntax-tree)

# scenario: match and derive "config props" inline within markdown

- Multiple blocks (anywhere within root level of MD)
- Languages:
  - YAML
  - Typescript
  - TOML (?)

Sample test:

![image](https://user-images.githubusercontent.com/185555/194806401-5e6175c7-b5fa-47ad-b379-7b1f9f8a11e1.png)

**Comment by philcockfield** [comment]
https://github.com/rowanyeoman/tdb.meeting/blob/main/undp/2.core-narratives/perspective-shift.md?plain=1#L1

```yaml
type: "action:todo"
payload: {
  title: "Move this to UN sections"
  detail: "Surveying all of the projects, reports and..."    <== Markdown.
  tags: ["Draft-1"]
}
```

type: `TODO:ACTION`
example: "Move this to UN sections"

<img width="662" alt="image" src="https://user-images.githubusercontent.com/185555/194995851-31291274-f2e8-4a53-b77a-11d688f12bcf.png">

Example usages when extracted from entire corpus:

- isolate list of NEXT ACTIONS
- hide in "publish/display mode"
- as as collaboration `reference` hooks in other "Meeting Doc" action data structures.
